server:
  port: 8080
  servlet:
    context-path: /fundrating
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fund_rating?useSSL=false&noAccessToProcedureBodies=true&autoReconnect=True&reWriteBatchedInserts=true
    username: pavi
    password: root
security:
  ignoreUrl: /**
